#!/bin/bash

CONFIG_FILE=$(realpath "$HOME/.config/niri/config.kdl")
CURRENT_LAYOUT=$(niri msg keyboard-layouts | grep '^\s*\* ' | sed 's/^\s*\* [0-9][0-9]* //g')

niri msg action switch-layout next
pkill -SIGRTMIN+10 waybar

notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low "Layout changed to $(niri msg keyboard-layouts | grep '^\s*\* ' | sed 's/^\s*\* [0-9][0-9]* //g')"
