#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
## Edited by yurihikari

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/powermenu.rasi"
CNFR="$DIR/rofi/confirm.rasi"

# Theme Elements
prompt=$USER" ("$(hostname)")"
mesg="Uptime : `uptime -p | sed -e 's/up //g'`"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
title_option_1="  Lock         "
title_option_2=" 󰍃 Log Out      "
title_option_3="  Suspend      "
title_option_4="  Hibernate    "
title_option_5="  Reboot       "
title_option_6="  Shut Down    "
if [[ "$layout" == 'NO' ]]; then
	option_1=" Lock"
	option_2="󰍃 Logout"
	option_3=" Suspend"
	option_4=" Hibernate"
	option_5=" Reboot"
	option_6=" Shutdown"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6=""
fi
cnflayout=`cat ${CNFR} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$cnflayout" == 'NO' ]]; then
	yes=' Yes'
	no=' No'
else
	yes=''
	no=''
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-p "$1" \
		-mesg 'Are you Sure?' \
		-theme ${CNFR}
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd "$1"
}

# Confirm and execute
confirm_run () {	
	selected="$(confirm_exit "$1")"
	if [[ "$selected" == "$yes" ]]; then
        ${2} && ${3} && ${4} && ${5}
    else
        exit
    fi	
}

# Execute Command
run_cmd() {
	if [[ "$1" == "$option_1" ]]; then
		sleep 0.5 && hyprlock
	elif [[ "$1" == "$option_2" ]]; then
		confirm_run "$title_option_2" 'hyprctl dispatch exit 0'
	elif [[ "$1" == "$option_3" ]]; then
		confirm_run "$title_option_3" 'mpc -q pause' 'pulsemixer --mute' "hyprlock" 'systemctl suspend'
	elif [[ "$1" == "$option_4" ]]; then
		confirm_run "$title_option_4" 'systemctl hibernate'
	elif [[ "$1" == "$option_5" ]]; then
		confirm_run "$title_option_5" 'systemctl reboot'
	elif [[ "$1" == "$option_6" ]]; then
		confirm_run "$title_option_6" 'systemctl poweroff'
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd "$option_1"
        ;;
    $option_2)
		run_cmd "$option_2"
        ;;
    $option_3)
		run_cmd "$option_3"
        ;;
    $option_4)
		run_cmd "$option_4"
        ;;
    $option_5)
		run_cmd "$option_5"
        ;;
    $option_6)
		run_cmd "$option_6"
        ;;
esac
