#!/bin/bash

# Switch to the next keyboard layout
hyprctl switchxkblayout at-translated-set-2-keyboard next > /dev/null

# Get the active keyboard layout name
layout=$(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap')

# Send notification
notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low "Layout changed to $layout"

