#!/bin/bash
# Fuzzy package search and install (source: https://github.com/basecamp/omarchy/blob/master/bin/omarchy-pkg-install)

fzf_args=(
  --multi
  --preview 'paru -Sii {1}'
  --preview-label='alt-p: toggle description, alt-j/k: scroll, tab: multi-select'
  --preview-label-pos='bottom'
  --preview-window 'down:50%:wrap'
  --bind 'alt-p:toggle-preview'
  --bind 'alt-d:preview-half-page-down,alt-u:preview-half-page-up'
  --bind 'alt-k:preview-up,alt-j:preview-down'
  --color 'pointer:green,marker:green'
)

pkg_names=$(paru -Slq | fzf "${fzf_args[@]}")

if [[ -n "$pkg_names" ]]; then
  # Convert newline-separated selections to space-separated for yay/paru
  paru -S $(echo "$pkg_names" | tr '\n' ' ')
fi
